<a id="7"></a>
## Practice Task 1

Practice on a dataset: **tips** — restaurant bills and tips. Load it and answer the questions below. (Solutions are not provided on purpose — everything you need is in this notebook.)

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

tips = sns.load_dataset("tips")

In [4]:
tips.head() # Show first 5 of the dataset

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
tips.tail() # Show last 5 of the dataset

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [10]:
tips.sample(5, random_state=42) # Show random 5 of the dataset and allways show the same random 5 rows by setting random_state=42

     total_bill   tip     sex smoker   day    time  size
24        19.82  3.18    Male     No   Sat  Dinner     2
6          8.77  2.00    Male     No   Sun  Dinner     2
153       24.55  2.00    Male     No   Sun  Dinner     4
211       25.89  5.16    Male    Yes   Sat  Dinner     4
198       13.00  2.00  Female    Yes  Thur   Lunch     2

In [14]:
# tips.describe() # Show summary of the dataset with numerical columns
# tips.describe(exclude='number') # show summary of the dataset excluding numerical columns
tips.describe(include='all') # show all columns of the dataset

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [8]:
tips.info() # Show information of the dataset

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

**Exercise 1.** How many rows and columns does `tips` have? Which columns are numeric and which are categorical? Are any values missing?

**Exercise 2.** Show summary statistics for the numeric columns. What is the largest total bill?

**Exercise 3.** How many smokers vs. non-smokers are in the data? (Hint: `value_counts`.)

**Exercise 4.** Select all rows where the bill is above 40 dollars *and* the party size is at least 4. How many are there?

**Exercise 5.** Using `groupby`, compute the average tip for each day of the week. Which day tips best?

In [15]:
# Exercise 1
print("Rows and Colums:", tips.shape)
tips.info()

Rows and Colums: (244, 7)
<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [16]:
# Exercise 2

print("Largest Total Bill:", tips['total_bill'].max())
tips.describe()

Largest Total Bill: 50.81

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
# Exercise 3
tips['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [18]:
# Exercise 4
data = tips[(tips['total_bill'] > 40) & (tips['size'] > 4)]
print(data)

     total_bill  tip   sex smoker   day    time  size
142       41.19  5.0  Male     No  Thur   Lunch     5
156       48.17  5.0  Male     No   Sun  Dinner     6

In [19]:
# Exercise 5
mean_tip = tips.groupby('day')['tip'].mean().round(2)
print(mean_tip)
print("Best Day: ", mean_tip.idxmax())

day
Thur    2.77
Fri     2.73
Sat     2.99
Sun     3.26
Name: tip, dtype: float64
Best Day:  Sun