### The cleaning checklist 

1. `info()` + `isna().sum()` — what is missing, what has the wrong type?
2. Decide per column: drop or fill? **Write down your choice and the reason.**
3. Check duplicates — inspect before dropping.
4. Fix dtypes (numbers, categories, dates).
5. Clean text columns; standardize column names.
6. Look for outliers; decide keep / cap / remove — and say so.
7. Save the cleaned file and use it for everything that follows.

<a id="8"></a>
## 8. Lets Try

Below is a small, deliberately messy dataset. Apply the full checklist to it.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

messy = pd.DataFrame({
    "Name ": ["  alice", "Bob", "bob", "CHARLIE ", "dana", "Bob", None],
    "Age": ["25", "32", "32", "199", "28", "32", "41"],
    "City": ["Dhaka", " dhaka", "Chittagong", "Dhaka", None, " dhaka", "Sylhet"],
    "Salary($)": ["50,000", "62,000", "62,000", "58,000", "n/a", "62,000", "71,000"],
})
messy

      Name   Age        City Salary($)
0     alice   25       Dhaka    50,000
1       Bob   32       dhaka    62,000
2       bob   32  Chittagong    62,000
3  CHARLIE   199       Dhaka    58,000
4      dana   28        None       n/a
5       Bob   32       dhaka    62,000
6      None   41      Sylhet    71,000

**Exercise 1.** Standardize the column names: strip spaces, lowercase, and replace `($)` so the names are valid identifiers like `salary`.

**Exercise 2.** `Age` is stored as text and contains an impossible value. Convert it to numeric and deal with the 199. Justify your choice.

**Exercise 3.** Clean the `Name` and `City` text (strip, consistent case), then find and remove the truly duplicated row.

**Exercise 4.** Convert `Salary($)` to numeric (careful: commas and `"n/a"`), then fill the missing salary with a value you think is reasonable — and write one sentence defending the choice.

**Exercise 5.** Save your cleaned DataFrame to `messy_clean.csv` and reload it to verify.

In [ ]:
# Exercise 1
messy.columns = messy.columns.str.strip().str.lower().str.replace('($)','')
messy.columns

Index(['name', 'age', 'city', 'salary'], dtype='object')

In [ ]:
# Exercise 2
messy['age'] = pd.to_numeric(messy['age'], errors = 'coerce')
messy.loc[messy['age'] > 120, 'age'] = np.nan
age_median = messy['age'].median()
messy['age'] = messy['age'].fillna(age_median)
messy['age']

0    25.0
1    32.0
2    32.0
3    32.0
4    28.0
5    32.0
6    41.0
Name: age, dtype: float64

In [ ]:
messy_duplicate = messy.copy()
messy_duplicate['name'] = messy_duplicate['name'].str.strip().str.title()
messy_duplicate['city'] = messy_duplicate['city'].str.strip().str.title()
messy_duplicate = messy_duplicate.drop_duplicates()
messy_duplicate['city'] = messy_duplicate['city'].fillna(messy_duplicate['city'].mode()[0])
messy_duplicate

      name   age        city  salary
0    Alice  25.0       Dhaka  50,000
1      Bob  32.0       Dhaka  62,000
2      Bob  32.0  Chittagong  62,000
3  Charlie  32.0       Dhaka  58,000
4     Dana  28.0       Dhaka     n/a
6     None  41.0      Sylhet  71,000

In [ ]:
# Exercise 4
messy_duplicate['salary'] = messy_duplicate['salary'].str.replace(',', '').str.replace('n/a', '')
messy_duplicate['salary'] = pd.to_numeric(messy_duplicate['salary'], errors='coerce')
messy_duplicate['salary'] = messy_duplicate['salary'].fillna(messy_duplicate['salary'].median())
messy_duplicate

      name   age        city   salary
0    Alice  25.0       Dhaka  50000.0
1      Bob  32.0       Dhaka  62000.0
2      Bob  32.0  Chittagong  62000.0
3  Charlie  32.0       Dhaka  58000.0
4     Dana  28.0       Dhaka  62000.0
6     None  41.0      Sylhet  71000.0

In [ ]:
# Exercise 5

messy_duplicate.to_csv('messy_clean.csv', index = False)
check = pd.read_csv('messy_clean.csv')
print("saved and reloaded:", check.shape)
check.head()

saved and reloaded: (6, 4)

      name   age        city   salary
0    Alice  25.0       Dhaka  50000.0
1      Bob  32.0       Dhaka  62000.0
2      Bob  32.0  Chittagong  62000.0
3  Charlie  32.0       Dhaka  58000.0
4     Dana  28.0       Dhaka  62000.0